.\" A sample man page. 
.\" Contact admin@yourcompany.com to correct errors or omissions. 
.TH man 1 "07 December 2003" "1.0" "Sample man page"
.SH NAME
sample \- a sample man page
.SH SYNOPSIS
.\" Syntax goes here. 
.B man sample
.SH EXAMPLES
man pages will often contain examples following the 
.B SYNOPSIS
.SH DESCRIPTION
.B sample
is a sample man page. 
.SH OPTIONS
The sample man page is not a program, and does not take any options.
.SH FILES
.P 
.I /usr/share/man/man1/sample.1.gz
.SH SEE ALSO
.BR man (1), 
.BR man (7),
.BR apropos (1),
.BR less (1),
.BR groff (1), 
.BR catman (8)
.SH BUGS
No known bugs at this time. 
.SH LIST
.IP \(bu 2 
List item
.IP \(bu 2 
List item 2
.SH AUTHOR
.nf
Joe "Zonker" Brockmeier (jzb@dissociatedpress.net)
.fi
.SH HISTORY
2003 \- Written as an example template for other man pages.
