.TH man 1 "2 April 2007" "0.1" "InMind man page"
.SH NAME
InMind \- InMind man mage
.SH SYNOPSIS
.B Inmind , high performance dns cacher/forwader
.SH EXAMPLES
inmind -v -i 127.0.0.1 -p 55 -i 1.1.1.1 -n 4.4.4.4 -n 2.2.2.2 -n 3.3.3.3 
.nf
this server will listen on 127.0.0.1 and use all -n arguments as nameserver.
.SH DESCRIPTION
.B InMind is high performance dns cacher , its aimed to get used on Mail/Cacher server , home gateway machines and etc . note that entries on inmind never get expired .
.SH OPTIONS
-i specify local address to bind to.
.nf
-n add Nameserver to list of nameservers , /etc/resolv.conf will get used by default.e
.nf
-p Listeting udp port.
.nf
-v to be little more verbose.
.nf
--help to see this message.
.nf
.SH BUGS
its kind of slow on more than 500 requset per second .
.SH AUTHOR
.nf
Armin ranjbar <zoup@zoup.org>
.fi
